# More information about this section can be found in the following location
# https://docs.gitlab.com/ee/ci/yaml/#include

include:
  - local: "acmecorp.apexaltruism.net/import.yml"
  - local: "apexaltruism.net/import.yml"
  - local: "blog.apexaltruism.net/import.yml"
  - local: "chat.apexaltruism.net/import.yml"
  - local: "code.apexaltruism.net/import.yml"
  - local: "dash.apexaltruism.net/import.yml"
  - local: "download.apexaltruism.net/import.yml"
  - local: "explorer.apexaltruism.net/import.yml"
  - local: "jump.apexaltruism.net/import.yml"
  - local: "leantime.apexaltruism.net/import.yml"
  - local: "play.apexaltruism.net/import.yml"
  - local: "stream.apexaltruism.net/import.yml"
  - local: "taskplan.apexaltruism.net/import.yml"
  - local: "transfer.apexaltruism.net/import.yml"
  - local: "transmission.apexaltruism.net/import.yml"
  - local: "vscode-main.apexaltruism.net/import.yml"
  - local: "wirezone.apexaltruism.net/import.yml"
  - local: "work.apexaltruism.net/import.yml"
  - local: "zone.apexaltruism.net/import.yml"

# Mirror the source repository available on GitLab to the destination 
# repository available on GitHub whenever a push is made to the primary branch
# of the source repository.

push-sync-github:
  stage: "test"
  image: "fedora:latest"
  script:
    - echo "Install Git and its dependencies"
    - dnf install git --setopt=install_weak_deps=False --assumeyes
    - echo "Adding destination repository as a remote"
    - git --git-dir=$CI_PROJECT_DIR/.git remote add $CI_COMMIT_SHORT_SHA https://t0xic0der:$githubac@github.com/t0xic0der/frontier.git
    - echo "Pushing the changes to the destination repository"
    - git --git-dir=$CI_PROJECT_DIR/.git push $CI_COMMIT_SHORT_SHA HEAD:main
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

# The initial stage requires setting proper permissions for the keyfiles
# This is to ensure that the "Host key verification failed" error is avoided
# This error happens due to the "UNPROTECTED PRIVATE KEY FILE" error

.deployment-prep:
  stage: "deploy"
  image: "fedora:37"
  before_script:
    - echo "Setup secure shell client configuration for automatic authentication"
    - mkdir -p "/root/.ssh/" && chmod 700 "/root/.ssh/"
    - cat "$privcode_trsa" > "/root/.ssh/id_rsa" && chmod 600 "/root/.ssh/id_rsa"
    - cat "$publcode_trsa" > "/root/.ssh/id_rsa.pub" && chmod 644 "/root/.ssh/id_rsa.pub"
    - cat "$sshdconf" > "/root/.ssh/config" && chmod 644 "/root/.ssh/config"
    - echo "Install 'Ansible' package required for setting up the configuration files"
    - dnf install "ansible" --setopt=install_weak_deps=False --assumeyes
    - echo "Install 'OpenSSH Clients' package required for setting up the configuration files"
    - dnf install "openssh-clients" --setopt=install_weak_deps=False --assumeyes
    - echo "Install 'Docker CE' package required for deploying the stated service"
    - dnf install "dnf-plugins-core" --setopt=install_weak_deps=False --assumeyes
    - dnf config-manager --add-repo "https://download.docker.com/linux/fedora/docker-ce.repo"
    - dnf install "docker-ce" "docker-compose-plugin" --setopt=install_weak_deps=False --assumeyes

# Pre-defined variables reference can be found in the following location
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
