# Frontier
# Copyright (C) 2023 Akashdeep Dhar

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Reference for CI pipeline file was taken from the following location
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# Pre-defined variables reference can be found in the following location
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

# The initial stage requires setting proper permissions for the keyfiles
# This is to ensure that the "Host key verification failed" error is avoided
# This error happens due to the "UNPROTECTED PRIVATE KEY FILE" error

image: fedora:latest

before_script:
  - echo "Setup secure shell client configuration for automatic authentication"
  - mkdir -p "/root/.ssh/" && chmod 700 "/root/.ssh/"
  - cat "$privcode_trsa" > "/root/.ssh/id_rsa" && chmod 600 "/root/.ssh/id_rsa"
  - cat "$publcode_trsa" > "/root/.ssh/id_rsa.pub" && chmod 644 "/root/.ssh/id_rsa.pub"
  - cat "$sshdconf" > "/root/.ssh/config" && chmod 644 "/root/.ssh/config"
  - echo "Install 'Ansible' package required for setting up the configuration files"
  - dnf install "ansible" --setopt=install_weak_deps=False --assumeyes
  - echo "Install 'OpenSSH Clients' package required for setting up the configuration files"
  - dnf install "openssh-clients" --setopt=install_weak_deps=False --assumeyes
  - echo "Install 'Docker CE' package required for deploying the stated service"
  - dnf install "dnf-plugins-core" --setopt=install_weak_deps=False --assumeyes
  - dnf config-manager --add-repo "https://download.docker.com/linux/fedora/docker-ce.repo"
  - dnf install "docker-ce" "docker-compose-plugin" --setopt=install_weak_deps=False --assumeyes

serve_jump.apexaltruism.net:
  stage: "deploy"
  environment: "jump.apexaltruism.net"
  variables:
    hostname: "$CI_ENVIRONMENT_NAME"
  script:
    - echo "Implement the compose configuration file using the stored variable file"
    - cat "$variable_jump" > "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - ansible-playbook "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/prepbook.yml" --extra-vars "@$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - echo "Deploy the stated service on the specified inventory location"
    - docker --host "$location_centvirt_slva" compose --file "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/compconf.yml" up --detach
  only:
    changes:
      - "jump.apexaltruism.net/compconf.template.j2"
      - "jump.apexaltruism.net/prepbook.yml"
      - "jump.apexaltruism.net/serve"

cease_jump.apexaltruism.net:
  stage: "deploy"
  environment: "jump.apexaltruism.net"
  variables:
    hostname: "$CI_ENVIRONMENT_NAME"
  script:
    - echo "Implement the compose configuration file using the stored variable file"
    - cat "$variable_jump" > "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - ansible-playbook "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/prepbook.yml" --extra-vars "@$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - echo "Deploy the stated service on the specified inventory location"
    - docker --host "$location_centvirt_slva" compose --file "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/compconf.yml" down
  only:
    changes:
      - "jump.apexaltruism.net/compconf.template.j2"
      - "jump.apexaltruism.net/prepbook.yml"
      - "jump.apexaltruism.net/cease"

serve_download.apexaltruism.net:
  stage: "deploy"
  environment: "download.apexaltruism.net"
  variables:
    hostname: "$CI_ENVIRONMENT_NAME"
  script:
    - echo "Implement the compose configuration file using the stored variable file"
    - cat "$variable_download" > "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - ansible-playbook "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/prepbook.yml" --extra-vars "@$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - echo "Deploy the stated service on the specified inventory location"
    - docker --host "$location_centvirt_slva" compose --file "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/compconf.yml" up --detach
  only:
    changes:
      - "download.apexaltruism.net/compconf.template.j2"
      - "download.apexaltruism.net/prepbook.yml"
      - "download.apexaltruism.net/serve"

cease_download.apexaltruism.net:
  stage: "deploy"
  environment: "download.apexaltruism.net"
  variables:
    hostname: "$CI_ENVIRONMENT_NAME"
  script:
    - echo "Implement the compose configuration file using the stored variable file"
    - cat "$variable_download" > "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - ansible-playbook "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/prepbook.yml" --extra-vars "@$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/variable.json"
    - echo "Deploy the stated service on the specified inventory location"
    - docker --host "$location_centvirt_slva" compose --file "$CI_PROJECT_DIR/$CI_ENVIRONMENT_NAME/compconf.yml" down
  only:
    changes:
      - "download.apexaltruism.net/compconf.template.j2"
      - "download.apexaltruism.net/prepbook.yml"
      - "download.apexaltruism.net/cease"
